---
swagger: "2.0"
info:
  description: "This is an example of using OAuth2 Application Flow in a specification\
    \ to describe security to your API."
  version: "1.0.0"
  title: "Sample Application Flow OAuth2 Project"
host: "virtserver.swaggerhub.com"
basePath: "/sethbergman/auth-api/1.0.0"
schemes:
- "https"
security:
- application:
  - "read"
  - "write"
paths:
  /example:
    get:
      summary: "Server example operation"
      description: "This is an example opeartion to show how security is applied to\
        \ the call."
      operationId: "exampleGET"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Default"
  /ping:
    get:
      summary: "Server heartbeat operation"
      description: "This operation shows how to override the global security defined\
        \ above, as we want to open it up for all users."
      operationId: "pingGET"
      parameters: []
      responses:
        200:
          description: "OK"
      security: []
      x-swagger-router-controller: "Default"
securityDefinitions:
  application:
    type: "oauth2"
    tokenUrl: "http://example.com/oauth/token"
    flow: "application"
    scopes:
      write: "allows modifying resources"
      read: "allows reading resources"
definitions: {}
